### ISSUE TITLE
Multidimensional Labels 

### ISSUE THREAD

**Issue by lolz0r** [cvjena/cn24#26]
Hello,
I have been reading though the docs for CN24. Is it possible to setup a .set file such that the output has 3 channels (Red, Green, Blue) where the number of actual "classifications" is 2^24? 

Essentially I want to train a network to output an RGB image based on a different RGB image.

Please let me know if this is possible.

**Comment by clrokr** [comment]
Hi,
currently this is not possible using only the built-in tools. However, this should be a simple fix to the makeTensorStream tool. You are welcome to submit a pull request if you feel comfortable changing the code yourself. If you don't, we will add this to the v2.0 release of CN24.

**Comment by lolz0r** [comment]
Thanks for the idea - I added a pull request to this repo. Feel free to use it if you would like. :)
