### ISSUE TITLE
High CPU, no GPU utilization in training

### ISSUE THREAD

**Issue by zygmuntz** [cvjena/cn24#35]
Hi,

I started training, the log shows the GPU:

	INF [ CLHelper::Init(216) ] Using OpenCL device: GRID K520
	DBG [ CLHelper::Init(217) ] Image support: Yes
	DBG [ CLHelper::Init(228) ] Creating OpenCL context...
	DBG [ CLHelper::Init(239) ] Creating OpenCL command queue...

And then:

	 > train

	INF [ Trainer::Epoch(156) ] Epoch: 0, it: 500, bsize: 16, current lr: 0.0001
 
[nothing happens]
[when setting the `method=patch`, the progress is prompt]

I'm seeing all 8 CPUs at 100%, but `nvidia-smi` indicates little GPU usage. What does this mean?

    FB Memory Usage
        Total                       : 4095 MiB
        Used                        : 64 MiB
        Free                        : 4031 MiB
    BAR1 Memory Usage
        Total                       : 128 MiB
        Used                        : 2 MiB
        Free                        : 126 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 0 %
        Encoder                     : 0 %
        Decoder                     : 0 %
    Temperature
        GPU Current Temp            : 41 C
        GPU Shutdown Temp           : 97 C
        GPU Slowdown Temp           : 92 C
    Power Readings
        Power Management            : Supported
        Power Draw                  : 42.09 W
        Power Limit                 : 125.00 W
        Default Power Limit         : 125.00 W
        Enforced Power Limit        : 125.00 W
        Min Power Limit             : 85.00 W
        Max Power Limit             : 130.00 W
    Clocks
        Graphics                    : 797 MHz
        SM                          : 797 MHz
        Memory                      : 2500 MHz
    Compute Processes
        Process ID                  : 20643
            Name                    : /home/ubuntu/cn24/build/trainNetwork
            Used GPU Memory         : 52 MiB

**Comment by clrokr** [comment]
Hi,
are you sure you're using clBLAS? 52 MB is very a low memory usage!

**Comment by zygmuntz** [comment]
Ooops... Apparently I used the older version without clBLAS. When running with clBLAS, I get this (both in normal/patch mode):

	 > train

	INF [ Trainer::Epoch(156) ] Epoch: 0, it: 500, bsize: 16, current lr: 0.0001
	OpenCL error -11 on line 163 of /home/ubuntu/clBLAS/src/library/blas/xgemm.cc
	trainNetwork: /home/ubuntu/clBLAS/src/library/blas/xgemm.cc:163: void makeGemmKernel(_cl_kernel**, cl_command_queue, const char*, const char*, const unsigned char**, size_t*, const char*): Assertion `false' failed.
	./trainnet.sh: line 3: 21393 Aborted                 (core dumped) /home/ubuntu/cn24/trainNetwork -v /home/ubuntu/data/config.set /home/ubuntu/data/arch.net
