### ISSUE TITLE
Bus error when testing

### ISSUE THREAD

**Issue by zygmuntz** [cvjena/cn24#36]
When I type `test`, the CPU usage goes up and nothing happens for about a minute, then a message appears about a bus error. Could this have to do with image size (1500x1500)?

	INF [ Trainer::Epoch(156) ] Epoch: 99, it: 500, bsize: 16, current lr: 2.33894e-06
	.....10%.....20%.....30%.....40%.....50%.....60%.....70%.....80%.....90%....
	DBG [ Trainer::Epoch(221) ] Training, sps: 8628.59
	DBG [ Trainer::Epoch(226) ] Training, tps: 115.894 us
	DBG [ Trainer::Epoch(232) ] Training, GB/s   up: 0.000128576
	DBG [ Trainer::Epoch(233) ] Training, GB/s down: 0.000128576
	INF [ Trainer::Epoch(241) ] Training (Epoch 99, node 0) Square Loss Layer (Weight: 1) lps: 0.138364
	INF [ Trainer::Epoch(243) ] Training (Epoch 99) aggregate lps: 0.138364
	RESULT --- Training  - Epoch 99 - F1 : 12.6683% (t=-1)
	RESULT --- Training  - Epoch 99 - ACC: 6.7625%
	RESULT --- Training  - Epoch 99 - PRE: 6.7625%
	RESULT --- Training  - Epoch 99 - REC: 100%
	RESULT --- Training  - Epoch 99 - FPR: 100%
	RESULT --- Training  - Epoch 99 - FNR: 0%
	DBG [ Trainer::Reset(80) ] Resetting Trainer state
	INF [ NetGraph&, Conv::NetGraph&, Conv::Trainer&, Conv::Trainer&, bool, std::string&)(296) ] Training complete.
	 > test

	DBG [ Trainer::Reset(80) ] Resetting Trainer state
	DBG [ DatasetInputLayer::SetTestingMode(242) ] Enabled testing mode.
	DBG [ Trainer::Test(90) ] ./trainnet.sh: line 3: 20806 Bus error               (core dumped) /home/ubuntu/cn24/build/trainNetwork -v /home/ubuntu/data/config.set /home/ubuntu/data/arch.net

**Comment by clrokr** [comment]
Hi,
it could. Could you attach a stack trace?

**Comment by zygmuntz** [comment]
This is a "no clBLAS" output, so closing.

**Comment by zygmuntz** [comment]
Confirmed that it has to do with test set size. Well, I guess one just has to use small sets for testing.

**Comment by clrokr** [comment]
Just for reference, we have no problems using >70GB datasets without any special measures. You may want to check your system configuration because CN24 does not do anything out of the ordinary in terms of system calls.

**Comment by zygmuntz** [comment]
@clrokr What kind of hardware (in terms of main and GPU memory) do you use for those datasets?

**Comment by clrokr** [comment]
Training usually takes place on a Xeon E3-1231v3 workstation with 16GB main memory and an R9 290X with 4GB of VRAM.
