### ISSUE TITLE
Network from the cn24 paper

### ISSUE THREAD

**Issue by MahmoudHamandi** [cvjena/cn24#51]
Dear all,

I am trying to replicate the network provided in "Constitutional Patch Networks with Spatial Prior for Road Detection and Urban Scene Understanding" using the cn24 library. 

I am having an error: WRN [ NetGraph::IsComplete(141) ] Net has no outputs!
The network is provided below:

# Network configuration
?convolutional kernels=12 size=7x7
?maxpooling size=2x2
?relu

?convolutional size=5x5 kernels=6
?relu

?fullyconnected neurons=48
?relu

?fullyconnected neurons=192
?spatialprior
?relu

?fullyconnected neurons=1
?tanh
?output

# Learning settings
l1=0.001
l2=0.0005
lr=0.0001
gamma=0.003
momentum=0.9
exponent=0.75
iterations=100
sbatchsize=10
pbatchsize=2

Thank you in advance.

**Comment by svensickert** [comment]
Dear Mahmoud,

unfortunately the table in the paper is incomplete. There is a third convolution layer missing. However, you can find the "correct" configuration for the task already in this repository. Please have a look in the sub directory "example". There you can find the "kitti.net" file which provides the architecture for the road detection experiments of the paper.

Best regards,
Sven
